### ISSUE TITLE
Build instructions for Ubuntu 14.04 are out of date

### ISSUE THREAD

**Issue by CruzR** [caffe2/caffe2.github.io#24]
The [build instructions for Ubuntu 14.04](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile) don't work as is. Issues I've run into so far:

- PyTorch's setup.py now checks for the `typing` module, so it needs to be added to the list of PyPI packages to install
- The `cmake` package ships CMake 2.8.12, but PyTorch seems to require CMake >= 3.5 to build, so the required package is `cmake3`

Does caffe2 still officially support Ubuntu 14.04? If not, docs should be changed to indicate that.

**Comment by orionr** [comment]
Hi @CruzR - thank you for the feedback. I think this was caused by our merge of PyTorch and Caffe2. You can still do a straight `mkdir build; cd build; cmake3 ..; make install` installation with cmake3, but the PR I just put up should fix this for `python setup.py install`.

**Comment by CruzR** [comment]
Thanks for the quick reply! To clarify, Ubuntu 14.04 actually installs CMake 3.5.1 as `/usr/bin/cmake`, you just need to install the `cmake3` package instead of the `cmake` package. I was more thinking of a simple documentation update, e.g.:

```diff
--- a/_docs/getting-started/ubuntu.md 2018-10-17 20:45:55.315365050 +0200
+++ b/_docs/getting-started/ubuntu.md 2018-10-17 20:47:24.015391864 +0200
@@ -52,7 +52,7 @@
 sudo apt-get update
 sudo apt-get install -y --no-install-recommends \
       build-essential \
-      cmake \
+      cmake3 \
       git \
       libgoogle-glog-dev \
       libgtest-dev \
@@ -71,7 +71,8 @@
 pip install --user \
       future \
       numpy \
-      protobuf
+      protobuf \
+      typing
 ```

I still didn't manage to make setup.py work for me, but that might be because my use case is somewhat exotic (I'm trying to install to a different directory with `setup.py install --prefix=/some/path` because I don't have write permissions for `/usr` or `/usr/local`). But the direct build using CMake works for me, thanks for the tip!

**Comment by orionr** [comment]
In that case you're probably in better shape then I thought. :) We definitely need to support cmake3 as the command, though, through `setup.py` so I'll still land the PR. An update on the docs would be great. Do you want to put up a PR? If not, I'll make the change.

Also, if you want to install locally I'd highly recommend conda and creating a conda environment that you can install in. Then you should be able to use `python setup.py install`.

**Comment by CruzR** [comment]
Sure, I can open a pull request, I just need some time to clone this repo first, my VPN is kind of slow at the moment.
