### ISSUE TITLE
Links "edit on github" are wrong

### ISSUE THREAD

**Issue by louisabraham** [caffe2/caffe2.github.io#6]
https://github.com/caffe2/caffe2.github.io/blob/6e905e97259f56bc75c70b8ef1cb1a619edc7295/_includes/doc.html#L21

https://github.com/caffe2/caffe2.github.io/blob/6e905e97259f56bc75c70b8ef1cb1a619edc7295/_includes/doc-getting-started.html#L39

https://github.com/caffe2/caffe2.github.io/blob/6e905e97259f56bc75c70b8ef1cb1a619edc7295/_includes/operators.html#L20

**Comment by orionr** [comment]
Thanks @louisabraham! Just fixed.
